version: "3.8"
services:

    # PHP Service
    php:
        container_name: phpconvenio
        build:
            context: .
            target: phpconvenio
            args:
                - APP_ENV=${APP_ENV}
        environment:
            - APP_ENV=${APP_ENV}
            - CONTAINER_ROLE=app
        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - 8001:8000
        depends_on:
            - database
        networks:
            - networkphplarconvenios    
    # Database Server
    #database:
    #    container_name: database
    #    image: mysql:8.0
    #    ports:
    #        -   3306:33060
    #    environment:
    #        - MYSQL_DATABASE=laravel8crud
              #- MYSQL_USER=root
              #- MYSQL_PASSWORD=root
    #        - MYSQL_ROOT_PASSWORD=root
    

    database:
          image: mysql:8.0
          ports:
            - 3000:3000
          expose:
            - "3000"
        # cap_add:
        #- SYS_NICE # CAP_SYS_NICE
          volumes:
            - ./cache/mysql:/var/lib/mysql
            - ./conf-mysql.cnf:/etc/mysql/conf.d/mysql.cnf
          environment:
           - MYSQL_DATABASE=convenios
           - MYSQL_USER=root
           - MYSQL_PASSWORD=password
           - MYSQL_ROOT_PASSWORD=password        
          restart: unless-stopped            
          volumes:
           - db-data:/var/lib/mysql
          networks:
             - networkphplarconvenios
networks: 
     networkphplarconvenios:        

volumes:
    db-data: ~
